### ISSUE TITLE
개발언어 선택 관련 이슈

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/HolaHola#4]
안녕하세요. 상의드리고 싶은 것이 있어 이슈 남겨요.

1. 개발 언어 선택.
우선 안드로이드 어플 제작 기준으로 생각해봤을 때
개발 언어 후보로 Kotlin과 cross-platform 언어인 Flutter, React-Native로 추려봤습니다. 
계획하고 있는 HolaHola가 depth가 깊거나 아주 복잡한 앱은 아니여서
어떤 언어를 선택하건 제약이 따를 것 같지 않고 자이로센서 컨트롤도 다 가능한 듯 합니다.

아직 js도 난이도있는 코딩을 잘 소화하지 못하는 것 같아서 다른 언어를 배우는 것이 이도 저도 아니게 될까봐 걱정이네요.
아직은 kotlin>Flutter>RN 순으로 생각중입니다.

언제나처럼 결정은 제가 하는 거겠지만
지금 제가 만들려는 앱에 잘 맞는 언어나 언어 선택에 관련해서 간단한 조언 부탁드려요.

언어를 결정하고 나면 그 언어 관련해서도 사전조사가 필요할 것 같아요.

감사합니다.

**Comment by jongfeel** [comment]
사실 언어의 문제는 아니고 안드로이드 개발에 대한 이해를 필요로 하기 때문에
저는 안드로이드 자체를 배울 수 있는 방법을 택하는 걸 추천합니다.
그러면 kotlin만 남게 되네요.

**Comment by WonjeongPark** [comment]
감사합니다!
