### ISSUE TITLE
미팅 전 이슈입니다.

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/HolaHola#5]
출근하자마자 오전에 올려야지 했는데, 일하다보니 벌써 3시가 넘었네요.

이제까지 한 것을 종합해 보면,
기능정의, 화면정의 일부 작성과 개발환경 세팅했습니다.
oauth는 흐름파악은 했고 직접 코드로 테스트 하려고 보니
kotiln이라는 언어가 처음이라 우선 익숙한 언어 js로 시도해볼까 하다가,

지금 제가 하는 것들이 앱을 만들기 위한 설계이기에 kotlin으로 하는 것이 맞을 것 같아 안드로이드 스튜디오 깔고 kotlin 아주 기본적인 문법 몇개만 쳐봤습니다.

조금 익숙해지면 oauth 포함해서 기타 앱 설계부분의 테스트 진행해야 할 것 같아요.

앱 구조가 아주 간단해서 올해안에는 완성하려고 하는데 진행속도가 느려서 반성해야겠어요.

미팅 전이라 종합적인 이슈를 적어봅니다.
부족하다 생각하시면 언제든지 말씀해주세요.

감사합니다.

**Comment by jongfeel** [comment]
오늘도 출근하셨군요.

얘기해야 할 것들을 따로 적어 둘게요.

- 개발 환경 세팅
- kotlin 익숙해지기
- OAuth 이해

이 정도겠군요.
