### ISSUE TITLE
33th schedule

### ISSUE THREAD

**Issue by jongfeel** [WonjeongPark/HolaHola#7]
### 주당 총 6시간

원하는 요일과 할당 시간을 미리 적은 후에 실천

실천하기 전에 계획을 세워 두고
실제 실천했는지 여부를 체크해 주세요.

**Comment by WonjeongPark** [comment]
## 05월01일(금)~05월07일(목) Plan

- [x]  금 2시간
- [x]  토 2시간
- [ ]  ~~수 2시간~~ --> 목 2시간

**Comment by WonjeongPark** [comment]
## 05월08일(금)~05월14일(목) Plan

- [x] 월 2시간
- [ ] 화 2시간
- [ ] 수 2시간

**Comment by WonjeongPark** [comment]
## 05월15일(금)~05월21일(목) Plan

- [x] 월 2시간
- [x] 화 2시간
- [ ] 수 2시간
